apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging-eks
  region: us-east-2

iam:
  withOIDC: true

vpc:
  cidr: 10.20.0.0/16

nodeGroups:
  - name: stage-workers
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: ohio
