apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production-eks
  region: us-east-2

iam:
  withOIDC: true

vpc:
  cidr: 10.30.0.0/16

nodeGroups:
  - name: production-workers
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyName: <UPDATE-EC2-KEY-NAME-HERE>
